#KGenerators made by Kryniowesegryderiusz (Krynio_ on spigot)
#https://www.spigotmc.org/resources/79246/
#Need help? Join KGenerators discord: https://discord.gg/BZRjhpP4Ab

#Choose lang file. Default possibilities are en, pl, ro, vi
#If you want to add your own language contact us on discord
lang: en

#By default generator will generate block only on air. Here you can add blocks, which will be replaced by generated block.
can-generate-instead:
  - WATER
  - LAVA

#Should "generators" lang section be sent by actionbar instad of chat?
generators-actionbar-messages: true

#How explosions should be handled, if there is generator inside explode area?
#0 - cancel explosion
#1 - drop generator
#2 - remove generator
explosion-handler: 0

#Per player generators options add bunch of features related to limiting
#pick up, usage and placing generator per player
#You can find more on https://github.com/Kryniowesegryderiusz/KGenerators/wiki/Per-Player-Generators
per-player-generators:
  #Enables limit, usage and pickup checks
  enabled: false
  #Set default overall place limit (count of all player's generators)
  #Set to -1 to disable that limit
  #Can be overwritten by permission: kgenerators.overallplacelimit.<limit>
  overall-place-limit: -1

#This configuration section is for configuring actions needed for particular features
#Possible modes: BREAK (avaible only for pick-up), LEFT_CLICK, RIGHT_CLICK, NONE (ex. because of gui usage)
#Item could be "ANY"
#Sneak indicates if shift pressed is required
actions:
  #Action, which will be used for picking up generators
  pick-up:
    mode: BREAK
    item: ANY
    sneak: true
  #Action, which will be used for opening generator gui
  open-gui:
    mode: RIGHT_CLICK
    item: ANY
    sneak: true
  #Action, which will be used for checking how much time left before regeneration
  time-left-check:
    mode: RIGHT_CLICK
    item: ANY
    sneak: false

#These settings are related to performance and its not recommended to set them too low
#Values are presented in ticks (20 ticks = 1 second)
#Changed values need server restart to affect plugin functioning
intervals:
  #How often should generators check if they should regenerate?
  #All generator delays should be a multiple of this number
  generation-check: 10
  #How often should holograms be updated?
  hologram-update: 20
  #How often should generators guis be updated?
  #Set -1 to not update GUI
  gui-update: 20