#KGenerators made by Kryniowesegryderiusz (Krynio_ on spigot)
#https://www.spigotmc.org/resources/79246/

#Check what *Optional* means and how does it work: https://github.com/Kryniowesegryderiusz/KGenerators/wiki/Configuration-disclaimer

settings:
  #Choose lang file. Default possibilities are en, pl
  lang: en
  #By default generator will generate block only on air. Here you can add blocks, which will be replaced by generated block.
  can-generate-instead:
  - WATER
  - LAVA
  #*Optional* per-player-generators is explained more on: https://github.com/Kryniowesegryderiusz/KGenerators/wiki/Per-Player-Generators
  per-player-generators:
    #*Optional* Enables limit, usage and pickup checks
    #If you are not using these set this to false - it will improve performance. You will be still able to use /kgenerators check
    #Disabled by default
    enabled: false
    #*Optional* Set default overall place limit (count of all player's generators)
    #Set to -1 to disable that limit
    #Can be overwritten by permission: kgenerators.overallplacelimit.<limit>
    #-1 by default
    overall-place-limit: -1
generators:
  #unique ID
  stone_generator:
    #Generator block.
    #ALWAYS use names from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    generator: END_STONE
    #Generator item name
    name: '&aStone generator'
    #Generator item lore
    lore:
    - '&6This is stone generator!'
    - '&6Place it to generate stone'
    #*Optional* Should generator item glow?
    #True by default
    glow: true
    #Delay between generations (in ticks: 20 = 1s))
    delay: 40 #2s
    #Type of generator.
    #Possible types:
    #single - block is generated instead of generator block
    #double - block is generated above generator block
    type: double
    #*Optional* Should generator immediately generate block after placing?
    #If not generator will wait time from delay option after placing
    #True by default
    generate-immediately-after-place: true
    #*Optional* Should generator spawn placeholder block after mining generated block and before next generation?
    #Type material if you want to use that feature or '' if you dont.
    #Generators dont have placeholder by default
    placeholder: RED_SANDSTONE
    #*Optional* Should pistons be able to move generated block and generate new one?
    #False by default
    allow-piston-push: true
    #*Optional* 
    per-player-generators:
      #Default number of placed generators of that type per player
      #Set to -1 to disable that limit
      #Can be overwritten by permission: kgenerators.placelimit.<generator_id>.<limit>
      place-limit: 10
      #Should only owner be able to pick up generator?
      only-owner-pickup: true
      #Should only owner be able to break blocks of that generator?
      #Disables also piston-push event
      #Doesnt work for third-party plugins ex. breaking blocks hoppers
      only-owner-use: false
    #Blocks generated by chance. Chance % is set by chance/allchances equation.
    #ALWAYS use names from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    chances:
      STONE: 100
  #This generator has only required settings. As you see you dont have to use all of them (https://github.com/Kryniowesegryderiusz/KGenerators/wiki/Configuration-disclaimer)
  ores_generator:
    generator: COAL_BLOCK
    name: '&aCoal ore generator'
    lore:
    - '&6This is ores generator!'
    - '&6Place it to generate ores'
    delay: 40
    type: single
    chances:
      COAL_ORE: 50
      IRON_ORE: 25
      GOLD_ORE: 15
      DIAMOND_ORE: 9
      EMERALD_ORE: 1 