#KGenerators made by Kryniowesegryderiusz (Krynio_ on spigot)
#https://www.spigotmc.org/resources/79246/
settings:
  #Choose lang file. Default possibilities are en, pl
  lang: en
  #By default generator will generate block only on air. Here you can add blocks, which will be replaced by generated block.
  can-generate-instead:
  - WATER
  - LAVA
generators:
  #unique ID
  stone_generator:
    #Generator block. No matter, which server version do you have use names from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    generator: END_STONE
    #Picked up generator item name
    name: '&aStone generator'
    #Picked up generator item lore
    lore:
    - '&6This is stone generator!'
    - '&6Place it to generate stone'
    #Should picked up generator item glow?
    glow: true
    #Delay between generations (in ticks)
    delay: 40
    #Should generator immediately generate block after placing?
    #If not generator will wait time from delay option after placing
    generate-immediately-after-place: true
    #Should generator spawn placeholder block after mining generated block and before next generation?
    #Type material if you want to use that feature or '' if you dont.
    placeholder: RED_SANDSTONE
    #Type of generator.
    #Possible types:
    #single - block is generated instead of generator block
    #double - block is generated above generator block
    type: double
    #Blocks generated by chance (%). No matter, which server version do you have use names from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    chances:
      STONE: 100
  ores_generator:
    generator: COAL_BLOCK
    name: '&aCoal ore generator'
    lore:
    - '&6This is ores generator!'
    - '&6Place it to generate ores'
    glow: true
    delay: 40
    generate-immediately-after-place: true
    placeholder: ''
    type: single
    chances:
      COAL_ORE: 50
      IRON_ORE: 25
      GOLD_ORE: 15
      DIAMOND_ORE: 9
      EMERALD_ORE: 1 