main: me.kryniowesegryderiusz.KGenerators.KGenerators
name: KGenerators
version: ${project.version}
author: Kryniowesegryderiusz (Krynio_ on spigot)
website: https://www.spigotmc.org/resources/79246/
description: Create your custom generators
softdepend: [Multiverse-Core, WorldGuard, SuperiorSkyblock2, BentoBox]
api-version: 1.13
commands:
  kgenerators: